stinc:
    image: ihciah/stinc
    volumes:
        - ./supervisor:/etc/supervisor:ro
        - ./tinc_conf:/etc/tinc:ro
        - ./dnsmasq.d:/etc/dnsmasq.d:ro
    restart: always
    privileged: true
    devices:
        - "/dev/net/tun:/dev/net/tun"
    ports:
        - "10086:8388/tcp"
        - "10086:8388/udp"
